### ISSUE TITLE
Crawler isn't able to crawl the server it's placed onto

### ISSUE THREAD

**Issue by bobdesaunois** [CompraBV/CompraSiteMapper#7]
Currently there's a crawler on VS4 but it's unable to crawl systems installed onto that server.
**Note:** the crawler **IS** capable of crawling systems installed on other servers from out VS4.

The HTTP response code received is also `0`

``` java
[root@vs4 /]# /usr/bin/java -jar /var/www/vhosts/vakantiehuizen.nl/httpdocs/sitemap/CompraSiteMapper.jar http://www.vakantiehuizen.nl/ /var/www/vhosts/vakantiehuizen.nl/httpdocs/sitemap/
[Bob's evil twin]: Going to explore the target: http://www.vakantiehuizen.nl/
[Bob's evil twin]: Could not connect to the given url.
java.net.ConnectException: Connection timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
        at sun.net.www.http.HttpClient.New(HttpClient.java:308)
        at sun.net.www.http.HttpClient.New(HttpClient.java:326)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at nl.compra.CompraCrawler.Crawler.ConnectToTarget(Crawler.java:57)
        at nl.compra.CompraCrawler.Crawler.<init>(Crawler.java:36)
        at nl.compra.CompraCrawler.Brain.SpawnCrawler(Brain.java:26)
        at nl.compra.CompraCrawler.Brain.Execute(Brain.java:37)
        at nl.compra.SiteMapGenerator.Program.<init>(Program.java:53)
        at nl.compra.SiteMapGenerator.Program.main(Program.java:90)
[Bob's evil twin]: The response code from the requested target remained a HTTP Response code other than 200. (Namely: 0)
Exception in thread "main" java.lang.RuntimeException: No URLs added, sitemap would be empty; you must add some URLs with addUrls
        at com.redfin.sitemapgenerator.SitemapGenerator.write(SitemapGenerator.java:160)
        at com.redfin.sitemapgenerator.WebSitemapGenerator.write(WebSitemapGenerator.java:14)
        at nl.compra.SiteMapGenerator.Program.<init>(Program.java:65)
        at nl.compra.SiteMapGenerator.Program.main(Program.java:90)


```

**Comment by bobdesaunois** [comment]
**Possibly relevant:** http://stackoverflow.com/questions/7219431/why-connection-to-localhost-is-refused

**Comment by bobdesaunois** [comment]
:cry: :sob: :100:
